apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no

resources:
  - ../../../base

labels:
  - pairs:
      app.kubernetes.io/instance: fint-flyt-egrunnerverv-dispatch-gateway_trondelagfylke_no
      fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelagfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/env/1/value"
        value: "https://vigoiks.service-now.com/api/now/table"
      - op: replace
        path: "/spec/env/2/value"
        value: "https://vigoiks.service-now.com/oauth_token.do"
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/fint-flyt-egrunnerverv-dispatch-gateway-out"
    target:
      kind: Application
      name: fint-flyt-egrunnerverv-dispatch-gateway

